Backend/accounts/urls.py
from . import views
from django.urls import path
# from django.contrib.auth import as auth_views

app_name = 'accounts' 
urlpatterns = [        
    path('',views.index, name='index'),
    path('register/', views.register, name='register'),
    path('login/', views.signin, name='signin'),
    path('logout', views.logout, name='logout'),
    # path('activate/<uidb64>/<token>', views.activate, name='activate'),
    # path('resetpassword', views.reset, name='resetpassword'),

    # Foget Password urls
    # path('forgotpassword/', views.forgot, name='forgot'),
    # path('forgotpassword/done/', views.done, name='done'),
    # path('reset/<uidb64>/<token>/', views.confirmview, name='confirm'),
    # path('reset/done/', views.resetcomplete, name='complete'),

    path('homepage/', views.homepage, name='home'),      
    path('contact', views.contact, name='contact'),
    path('documentation/', views.documentation, name='documentation'),
    path('library/<str:pk>/', views.library, name='library'),
    path('profile/<str:pk>/', views.profilepage, name='profile'),
    path('portfolio/<str:pk>/', views.portfolio, name='portfolio'),
    path('community/<str:pk>/', views.community, name='community'),
    path('edit/<str:pk>/', views.edit, name='edit'),
    path('team/', views.team, name='team'),
    path('start/', views.start, name='start'),
    path('important/', views.important, name='important'),
    path('usingclasses/', views.usingclasses, name='usingclasses'),
    path('usingJS/', views.usingJS, name='usingJS'),

] 

Backend/accounts/templates/accounts/activation_failed.html
{% autoescape off %}
    Activation failed, please try again.
{% endautoescape %}

Backend/accounts/templates/accounts/authheaderandfooter.html
<!DOCTYPE html>
<html lang="en">
  
<!-- HEADER -->
<head>
  <meta charset="UTF-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>{% block title %} {% endblock %}</title>
  {% load static %}
  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap" rel="stylesheet">
  <link rel="stylesheet" type="text/css" href="{% static '/css/anibry.css'%}">
    <link rel="shortcut icon" href="favicon.icon" type="library/x-icon">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,400,0,0" />
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
    <link rel="stylesheet" href="{% static '/css/headerandfooter.css'%}">

</head>
<body>
  <header>
    <div class="headercontainer">
      <a id="anibry-header-logo" href="/"><img src=" {% static '/imagesctn/images/anibry-logo-header.svg'%}" alt="logo"/></a>
      <div class="navmenu">
        <div class="innernav">
          <div class="closediv">
            <img class="close" src="{% static '/imagesctn/images/closeicon.svg'%}" alt="closeicon">
          </div>
          <a href="{% url 'accounts:library' user.id %}">Library</a>
          <a href="{% url 'accounts:documentation'%}">Documentation</a>
          <a href="{% url 'accounts:community' user.id %}">Community</a>
          <a href="{% url 'accounts:portfolio' user.id %}">Portfolio</a>
          <a href="{% url 'accounts:team'%}">Team</a>
          <a href="{% url 'accounts:contact'%}">Contact</a>
        </div>
      </div>
      <div class="profile">
          <!-- THIS USER-IMAGE CLASS SHOULD BE THE USER'S PICTURE -->
        <img class="user-image" src="{% static '/imagesctn/profilepage/profile-circle.png'%}" alt="profile-image" />
        <p class="profile-name"> {{user.username}} </p>
        <img class="icondown" src="{% static '/imagesctn/images/icondown.svg'%}" alt="icondown"/>
        <div class="hamburger">
          <img src="{% static '/imagesctn/images/menuhamburger.svg'%}" alt="hamburgericon">
        </div>
      </div>
    </div>

    <div class="headerdropdown">
      <div>
        <div class="profileindropdown">
          <!-- THIS USER-IMAGE CLASS BELOW SHOULD BE THE USER'S PICTURE -->
          <img class="user-image" src="{% static '/imagesctn/profilepage/profile-acircle.png'%}" alt="">
          <div class="details">
            <!-- THIS NAME BELOW SHOULD BE THE USER'S FULL NAME -->
            <p>{{user}}</p>
            <a href="{% url 'accounts:library' user.id %}">View Library</a>
          </div>
        </div>
      </div>
      <a class="gettingstarted" href="{% url 'accounts:start'%}">Getting Started</av>
      <a href="#">Account Settings</a>
      <a class="logout" href="{% url 'accounts:signin' %}">Log out</a>
    </div>
  </header>
{% block content %}
    <!-- FOOTER -->
{% endblock %}
  <footer>
    <div id="desktopfooter" class="footer-wrapper">
      <div class="footerColumnsContainer">
        <div class="footerCol footerCol1">
          <img src="{% static '/imagesctn/images/anibry-logo-footer.svg'%}" alt="logo" />
          <p>
            Build with all the love in the world by the using Anibry library
            in your projects. <br />
            Currently v1.0
          </p>
        </div>
        <div class="footerCol footerCol2">
          <a class="heading" href="#"><strong  style="color:white;"> Quick Link</strong></a>
          <a href="{% url 'accounts:library' user.id %}" style="color:white;">Library</a>
          <a href="{% url 'accounts:portfolio' user.id %}" style="color:white;">Anibry Portfolio</a>
          <a href="{% url 'accounts:profile' user.id %}" style="color:white;">Profile</a>
        </div>
        <div class="footerCol footerCol3">
          <a class="heading" href="#"><strong style="color:white;">Company</strong></a>
          <a href="{% url 'accounts:index' %}" style="color:white;">Home</a>
          <a href="{% url 'accounts:documentation' %}" style="color:white;">About Anibry</a>
          <a href="{% url 'accounts:team'%}" style="color:white;">Team</a>
          <a href="#" style="color:white;">Terms of Service</a>
          <a href="#" style="color:white;">Policy Privacy</a>
          <a href="#" style="color:white;">Cookies Policy</a>
        </div>
        <div class="footerCol footerCol4">
          <a class="heading" href="#"><strong style="color:white;">Help</strong></a>
          <a href="#" style="color:white;">FAQ</a>
          <a href="{% url 'accounts:documentation' %}" style="color:white;">Documentation</a>
          <a href="{% url 'accounts:contact'%}" style="color:white;">Contact Us</a>
          <a href="{% url 'accounts:community' user.id %}" style="color:white;">Community</a>
        </div>
      </div>
      <div class="copyright" style="color:white;">© 2022 Anibry. All right reserved.</div>
    </div>
  </footer>
  <script src="{% static '/js/headerandfooter.js'%}"></script>
</body>
</html>
    

Backend/accounts/templates/accounts/documentation.html
{% extends  'accounts/authheaderandfooter.html' %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    {% load static %}

    <title>{% block title %} Documentation | Anibry {% endblock %}</title>
    {% block content %}
     <link rel="stylesheet" type="text/css" href="{% static '/css/documentation.css'%}">
  </head>
  <body>
    <link rel="stylesheet" type="text/css" href="{% static '/css/documentation.css'%}">
    <div id="container">
      <img class="asidehamburger" src="{% static 'imagesctn\images\menuhamburger.svg' %}" alt="asidehamburger">
      <div class="aside">
        <div class="tableofcontent">
          <img class="closeasidemenu" src="{% static 'imagesctn\images\closeicon.svg' %}" alt="closeicon">
          <a href="{% url 'accounts:documentation'%}" class="active">Overview</a>
          <a href="{% url 'accounts:start'%}">Getting Started</a>
          <div id="listContent">
            <a href="{% url 'accounts:usingclasses'%}">Using Classes</a>
            <a href="{% url 'accounts:usingJS'%}">Using JavaScript</a>
          </div>
          <a href="{% url 'accounts:important'%}">Best Practices</a>
        </div>
      </div>
      <div id="content">    
        <h1>Anibry Library</h1>
        <p>
          Anibry is a library of ready-to-use, cross-browser animations for use in
          your web projects. Great for emphasis, home pages, sliders, and
          attention-guiding hints. Enjoy the fast, seamless, easy to use and easy
          to integrate library. Click here to download <a href="#" class="downloadbutton"> Anibry Library</a>
        </p>
      </div>
    </div>

    <script src="{%static '/js/documentation.js'%}"></script>
  </body>
  {% endblock %}
</html>

Backend/accounts/templates/accounts/editprofile.html
{% extends  'accounts/authheaderandfooter.html' %}
<title>{% block title %} Profile Page {% endblock %}</title>
<link rel="stylesheet" href="{% static '/css/style2.css'%}">

{% block content %}
<body>
    <header>
        <!-- <nav class="nav-bar">
            <img src=" {% static '/imagesctn/img/Logo-purple.png'%}" alt=""> 
            
            <ul>
                <li><a href="./Frontend/Library Page/library.html">Library</a></li>
                <li><a href="./Frontend/documentation.html">Documentation</a></li>
                <li><a href="./Frontend/community.html">Community</a></li>
                <li><a href="./Frontend/portfolio.html">Portfolio</a></li>
                <li><a href="./Frontend/Team page/Teampage.html">Team</a></li>
                <li><a href="./Frontend/Contact/contact.html">Contact</a></li>
                <li><a href=""><img src="img/" alt=""></a></li>
            </ul>
        </nav> -->
        <div class="header"></div>
    </header>
    <main>
        <div class="content">
        <!-- the left-side -->
        <div class="left">
            <div class="left-side">
                <h2>Primary Information</h2>
                <p><a href="#">About</a></p>
                <p><a href="#">Link</a></p>
                <p><a href="#">Change Password</a></p>
            </div>
            <p><a href="#" class="delete-txt">Delete My Account</a></p>
        </div>
    </div>

        <!-- ---------------the main information-------- -->
        <div class="content">
            <!-- Avartar -->
            <div class="img-setup"><img src="#" alt="">
                <button><input type="image" src="" alt="" placeholder="Change Photo">Change Photo</button>
                <h6>max file size:5mb</h6>
            </div>
            <div class="info">
                <h6>Primary Information</h6>
                <p>Fullname</p>
                <input type="text" name="Fullname" id="" placeholder="Harriet Olarenwaju">
                <p>Email Address</p>
                <input type="email" name="Email" id="" placeholder="harrietolarenwaju17@gmail.com">
                <p>Company</p>
                <input type="text" name="Company" id="" placeholder="Anibry">
                <p>Location</p>
                <input type="text" placeholder="State">
                <div class="drop-content">
                    <div class="drop-content"><button class="dropbtn">
                            Country </button>

                        <div class="dropdown-content">
                            <a href="#">Nigeria</a>
                            <a href="#">United states</a>
                            <a href="#">Ohio</a>
                            <a href="#">Norway</a>
                            <a href="#">United Kingdom</a>
                            <a href="#">Other</a>
                        </div>
                    </div>

                </div>
                <div class="about">
                    <h5>About Me</h5>
                    <input type="text" name="" id="" placeholder="Tell us about yourself">
                </div>
                <div class="links">
                    <div class="github"><img src="{% static '/imagesctn/img/Vector (10).png'%}">Github</img> <input type="url" name="" id=""
                            placeholder="@harrietola"></div>
                    <div class="behance"><img src="{% static '/imagesctn/img/Vector (11).png'%}">Behance</img> <input type="url" name="" id=""
                            placeholder="@harrietola"></div>
                    <div class="linkedin"><img src="{% static '/imagesctn/img/Vector (12).png'%}">Linkedin</img> <input type="url" name=""
                            id="" placeholder="@harrietola"></div>
                    <div class="add"><img src="{% static '/imagesctn/img/Vector (10) (copy).png'%}">Add new Links</img></div>
                    <div class="save">
                        <button type="submit"><a href="#">Save changes</a></button>
                    </div>
                </div>
                
    </main>
</body>
{% endblock %}
</html>

Backend/accounts/templates/accounts/forgot.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Forgot Password</title>
    <link rel="stylesheet" href="login.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@500;600;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    
</head>
<body>
  <main>
    <div class="box">
      <div class="left-box">
        <div class="zuri vov flash">
          <h2>Forgot Password?</h2>
          <br>
          <p id="forgotp">Enter the email address associated with this your account</p>
          <form id="forgot" action="GET">
            <div class="form-container">
              <br />
              <p>Email Address</p>
              <div class="inputs">
                <input type="email" placeholder="harrietolanrewaju@gmail.com" required />
              </div>
            </div>
            <br>
            <button type="submit">Submit email</button>
            <br>
            <p id="lol">Already have an Anibry account?<a href="login.html">Log in</a>
            </p>
          </div>
        </form>
        </div>
   
       <div class="zuri right-box">
       <div class="">
        <img src="registrationgif/Forgot password.gif" alt="">
            
            </div>
      </div>
    </div>
  </main>
  <footer>
      <div><small>© 2022 Anibry. All right reserved.</small></div>
  </footer>
  </body>
  </html>

Backend/accounts/templates/accounts/forgotpassword.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Forgot Password</title>
    {% load static %}
    <link rel="stylesheet" href="{% static '/css/headerandfooter.css'%}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@500;600;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    
</head>
<body>
  <main>
    <div class="box">
      <div class="left-box">
        <div class="zuri vov flash">
          <h2>Forgot Password?</h2>
          <br>
          <p id="forgotp">Enter the email address associated with this your account</p>
          <form id="forgot" action="GET">
            <div class="form-container">
              <br />
              <p>Email Address</p>
              <div class="inputs">
                <input type="email" placeholder="email" required />
              </div>
            </div>
            <br>
            <button type="submit">Submit email</button>
            <br>
            <p id="lol">Already have an Anibry account?<a href="/login">Log in</a>
            </p>
          </div>
        </form>
        </div>
   
       <div class="zuri right-box">
       <div class="">
        <img src="{% static 'imagesctn\registrationgif\Forgot password.gif' %}" alt="">
            
            </div>
      </div>
    </div>
  </main>
  </body>
  </html>

Backend/accounts/templates/accounts/homepage.html
{% extends  'accounts/authheaderandfooter.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
     {% load static %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    

    <title>{% block title %} Homepage {% endblock %}</title>
    {% block content %}
    <link rel="stylesheet" href="{% static '/css/homepage.css'%}">
</head>
<body>
    <main>
    <section class="section1">
        <div class="box1">
            <div class="innerbox">
                <div>
                    <h1>Welcome To <br> Anibry Library</h1>
                    <p>Anibry is a library of cross-browser animations ready to use in your web projects. Excellent for focus, webpages, transition effects, and organising indications.</p>
                
                    <button><a href="{% url 'accounts:library' user.id %}">Go to library</a></button>
                </div>             
            </div>
        </div>
        <div class="box2">
            <img src="{% static 'imagesctn/homepage/Programming blue_purple on Lottiefiles 2 (1).svg'%} " alt="">
        </div>
    </section>
    <div class="complogos" >
        <img src="{% static 'imagesctn/homepage/Group 65.svg' %}" alt="company logos">
    </div>
    <h2>Make use of preset Interactions</h2>
    <p>Need to add something simple? Choose from a collection of prebuilt interactions and animations and add them to your site with a just a few clicks.</p>
    <div class="items">
            <div class="pulse">

                <img src="{% static 'imagesctn/homepage/Pulse 1.svg' %}" alt="pulse">
            </div>
            <div class="slidee">
                
                <img  src="{% static 'imagesctn/homepage/Slide 1.svg' %}" alt="slidee">
            </div>
            <div class="jelloo">
                <img src="{% static 'imagesctn/homepage/Jello 1.svg' %}" alt="jelloo">

            </div>
            <div class="bounced">
                <img src="{% static 'imagesctn/homepage/Bounce 1.svg' %}" alt="bounced">

            </div>
            <div class="grow">
                
                <img src="{% static 'imagesctn/homepage/Grow1 1.svg' %}" alt="grow">
            </div>
            <div class="rotated">

                <img src="{% static 'imagesctn/homepage/Rotate 1.svg' %}" alt="rotated">
            </div>
            <div class="pop">

                <img src="{% static 'imagesctn/homepage/Pop 1.svg' %}" alt="pop">
            </div>
            <div class="wobb">
                <img src="{% static 'imagesctn/homepage/Wobble 1.svg' %}" alt="Wobble">

            </div>
    </div>
    <div class="viewlibrary">
        
        <a href="{% url 'accounts:library' user.id %}">View more in Library </a>
    </div>
    <div class="bigImge">
        <img src="{% static 'imagesctn/homepage/Frame 427319517.svg' %}" alt="image">
    </div>
    <h2>FAQ</h2>
    <h1>You have inquiries. We have the answers.</h1>
    <div class="faq">

        <a  class="faqq"> <p>  How can I create animations in the library? </p></a>
        <p>To simply toggle through the library list till you find an animation you are interested in. Click to preview a demo then click the "copy" button at the bottom. You can now paste the class name in your target element's class list <br></p>
        <a class="faqq"> <p>  Can I create my own specific animations in the library? </p></a>
        <p> No, you can't. You can, however, create specific animations with the library after download. See documentation page for guide. <br></p>
        <a class="faqq"> <p>  Can I save and download animations for further purposes? </p> </a>
        <p>Yes, you can! Simply click the love or download button in the library page to either save or download respectively. <br></p>
        <a class="faqq"> <p>  Will I be able to access all animations on the offline download? </p> </a>
        <p>Of course. Give it a try! <br></p>
    </div>
    <form action="#" class="newsletter">
        
        <label for="newsletter" >Stay up to date <br>
with our newsletter. </label>
    <div class="input">
        <input type="email" name="user-email" id="user-email" placeholder="Enter email address...">
        <input type="submit" value="Subscribe" class="submit">
    </div>

    </form>
</main>
<script src="{% static './js/homepage.js'%}"></script>
</body>
{% endblock %}
</html>

Backend/accounts/templates/accounts/importantanimationtips.html
{% extends  'accounts/authheaderandfooter.html' %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    {% load static %}

    <title>{% block title %} Important Tips | Anibry {% endblock %}</title>
    {% block content %}
     <link rel="stylesheet" type="text/css" href="{% static '/css/documentation.css'%}">
  </head>
  <body>
    
    <div id="container">
      <img
        class="asidehamburger"
        src="{% static '/imagesctn/images/menuhamburger.svg' %}"
        alt="asidehamburger"
      />
      <div class="aside">
        <div class="tableofcontent">
            <img class="closeasidemenu" src="{% static '/imagesctn\images\closeicon.svg' %}" alt="closeicon">
          <a href="{% url 'accounts:documentation'%}" class="active">Overview</a>
          <a href="{% url 'accounts:start'%}">Getting Started</a>
          <div id="listContent">
            <a href="{% url 'accounts:usingclasses'%}">Using Classes</a>
            <a href="{% url 'accounts:usingJS'%}">Using JavaScript</a>
          </div>
          <a href="{% url 'accounts:important'%}">Best Practices</a>
        </div>
      </div>
      <div id="content">
        <h1>Important Tips</h1>
        <p>
            As much as using animations add flavor your website and can greatly improve user experience, there are a few tips to always take note of that would help guide usage of animations.
        </p>
        <h2>Have a clear reason to animate</h2>
        <p>
            It's best to refrain from animating a component purely for show. The objective of using animations should be obvious, so keep that in mind. Bounce, flash, pulse, and other attention-grabbing animations should be utilized to draw the user's attention to something unique in your interface rather than just to make it more "flashy."
        </p>
        <p>
            To help users understand what is happening in the interface and to clearly indicate that it is changing states, entrance and exit animations should be employed.
        </p>
        <p>
            It doesn't mean you shouldn't add some excitement to the interface; just make sure your user isn't hindered by animations, and that such usage of animations won't slow down the page's performance.
        </p>
        <h2>The smaller the element you animate, the better</h2>
        <p>Animating large elements won't be very useful to the user and probably won't do anything but confuse them. In addition, there is a good likelihood that the animations will be subpar, leading to a poor user experience.</p>
        <h2>Don't animate root elements</h2>
        <p>
            Although it is feasible, you should refrain from animating the <span class="blue">html</span> or <span class="blue">body</span> tags. Some reports noted that this can result in strange browser issues. Furthermore, making the entire page "jiggle" wouldn't do much for your user experience. If this effect is what you need, surround your page with a container element and animate it as follows:
        </p>
        <div class="codearea">
            <span class="grey"><</span><span class="blue">body</span><span class="grey">></span> <br>
            &nbsp;&nbsp;<span class="grey"><</span><span class="blue">main</span> <span class="cloud">class</span> = <span class="brown"> "jiggle"</span><span class="grey">></span> <br>
            &nbsp; &nbsp; &nbsp;<span class="grey"> <span><</span>!-- Your code --<span>></span> </span> 
            <br>&nbsp;&nbsp; <span class="grey">< /</span><span class="blue">main</span><span class="grey">></span>
            <br> <span class="grey">< /</span><span class="blue">body</span><span class="grey">></span>
        </div>
        <h2>Infinite animations should be avoided</h2>
        <p>
            Although Anibry provides classes for generic and unique animations and the flexibility to make them run infinitely, you should generally reduce and, if possible, avoid using endless run animations. There are chances it might irritate your users.
        </p>
          <div>
            <div id="interaction">
              <p> Is this information above useful for you? <img class="likeit" src="{% static '/imagesctn/images/like.svg' %}" alt="thumbsup"> <img class="dislikeit" src="{% static '/imagesctn/images/dislike.svg' %}" alt="thumbsdown"> </p>
              <textarea name="documentationInteraction" id="documentationInteraction" cols="20" rows="30" placeholder="Tell us why in this comment section"></textarea>
            </div>
            <div class="submitandcancel">
              <input class="submit" type="submit" value="Send Comment">
              <input class="cancel" type="button" value="Cancel">
            </div>
          </div>
        </div>
      </div>
    </div>
    <script src="{%static '/js/documentation.js'%}"></script>
  </body>
  {% endblock %}
</html>

Backend/accounts/templates/accounts/usingJS.html
{% extends  'accounts/authheaderandfooter.html' %}
<!DOCTYPE html>
<html lang="en">
  <head>
    {% load static %}
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    {% load static %}

    <title>{% block title %} Using JS {% endblock %}</title>
    {% block content %}
     <link rel="stylesheet" type="text/css" href="{% static '/css/documentation.css'%}">
  </head>
  <body>
    
    <div id="container">
      <img
        class="asidehamburger"
        src="{% static '/imagesctn/images/menuhamburger.svg'%}"
        alt="asidehamburger"
      />
      <div class="aside">
        <div class="tableofcontent">
          <img class="closeasidemenu" src="{% static '/imagesctn/images/closeicon.svg'%}" alt="closeicon">
          <a href="{% url 'accounts:documentation'%}" class="active">Overview</a>
          <a href="{% url 'accounts:start'%}">Getting Started</a>
          <div id="listContent">
            <a href="{% url 'accounts:usingclasses'%}">Using Classes</a>
            <a href="{% url 'accounts:usingJS'%}">Using JavaScript</a>
          </div>
          <a href="{% url 'accounts:important'%}">Best Practices</a>
        </div>
      </div>
      <div id="content">
        <h1>Using JavaScript</h1>
        <p>
          Alternatively, you can make your animations even more dynamic by using JavaScript.<br> Create a Javascript file and link it to your html file appropriately. To make the process easy, you can just copy the code below and paste is inside the Javascript file you just created. <br> Next up is to change the "targetelement" in the JavaScript code to the ones you want to animate and the "animationname" to your desired animation classname. <br>
          That's it!
        </p>
        <div class="codearea">
          <pre>
                <code class="language-JS">
  const targetClass = document.querySelector("targetelement");

  let targetClassName = targetClass.innerHTML;

    targetClass.addEventListener("click", function () {

      targetelement.className = "anibry";

      targetelement.classList.add(`${animationname}`);

    }
  });
}
                </code>
            </pre>
        </div>
        <p>Your animation is all set! <br>Alternatively, you can use keyframes.</p>
        <div id="interaction">
          <p> Is this information above useful for you? <img src="{% static '/imagesctn/images/like.svg' %}" alt="thumbsup"> <img src="{% static '/imagesctn/images/dislike.svg' %}" alt="thumbsdown"> </p>
          <div>
            <div>
              <textarea name="documentationInteraction" id="documentationInteraction" cols="20" rows="30" placeholder="Tell us why in this comment section"></textarea>
            </div>
            <div class="submitandcancel">
              <input class="submit" type="submit" value="Send Comment">
              <input class="cancel" type="button" value="Cancel">
            </div>
          </div>
        </div>
      </div>
    </div>
    <script src="{% static '/js/documentation.js'%}"></script>
  </body>
  {% endblock %}
</html>